language: ruby
rvm:
  - 1.9.3
  - ree

before_install:
  - gem update --system
  - gem --version

env:
  - DB=postgresql

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare

before_script:
  - psql -c 'create database cadenero_test' -U postgres