language: ruby
rvm:
  - 1.9.3

before_install:
  - gem update --system
  - gem --version

env:
  - DB=postgresql

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace

before_script:
  - psql -c 'create database cadenero_test' -U postgres