# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  database: cadenero_development 
  min_messages: warning

test:
  adapter: postgresql
  database: cadenero_test 
  min_messages: warning
